framework:
    mailer:
        dns: 'smtp://autogestion@msaludsgo.gov.ar:hospitalCarro12!!@mail.msaludsgo.gov.ar:465'
        transports:
            smtp1:
                dns: 'smtp://autogestion@msaludsgo.gov.ar:hospitalCarro12!!@mail.msaludsgo.gov.ar:465'
            smtp2:
                dns: 'smtp://autogestion@cisb.gob.ar:Autogestion2024$@smtp.hostinger.com:465'