# config/packages/sonata_admin.yaml

sonata_admin:
    title: false
    persist_filters: true
    title_logo: sahse.png
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            - position: left
              type: sonata.admin.block.admin_list
            - position: right
              type: sonata.block.service.text
              settings:
                  content: >
                      <div class="container">
                          <div class="alert alert-warning" role="alert">
                          <h2>Informacion Importante</h2>
                          <hr>
                            <p>Recuerde que ya esta disponible la opcion de facturacion electronica con AFIP.</p>
                          </div>
                      </div>


sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
