# config/packages/sonata_admin.yaml

sonata_admin:
    title: false
    persist_filters: true
    title_logo: sahse.png
    security:
        handler: sonata.admin.security.handler.role

sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
