# config/packages/sonata_admin.yaml

sonata_admin:
    title: false
    persist_filters: true
    title_logo: sahse.png
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            - position: left
              type: sonata.admin.block.admin_list
            - position: right
              roles: [ROLE_AUTOGESTION,ROLE_USER_HOSPITAL]
              type: sonata.block.service.text
              settings:
                  content:
                      <div class="container">
                          <div class="alert alert-warning" role="alert">
                          <h2>Informacion Importante</h2>
                          <h4>- Se recuerda que deberá consultar periodicamente la documentacion solicitada por la Obra Social<br>
                            para evitar futuros débitos</h4>
                          </div>
                      </div>
            - position: right
              roles: [ROLE_HPGD]
              type: sonata.block.service.text
              settings:
                  content:



sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
