twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null

    form_themes:
        - ApplicationToolsBundle:Form:dependent_filtered_entity_widget.html.twig
        - ApplicationToolsBundle:Form:editable_combobox_widget.html.twig
        - ApplicationToolsBundle:Form:formfield_cloacker_widget.html.twig
        - '@SonataForm\Form\datepicker.html.twig'
        #- 'anexoii\busquedadni.html.twig'

application_tools:
    dependent_filtered_entities:
        area_by_dependencia:
            form_options:
                entity_alias: area_by_dependencia
                class: App:Area
                entity_field: area
                parent_entity_field: dependencia
                parent_form_field: dependencia
                choice_label: area
                no_result_msg: 'Sin resultados'
                placeholder: '--seleccionar--'
            search_options:
                role: ROLE_USER
                order_field: nombre
                order_direction: ASC
                
        dependencia_by_organismo:
            form_options:
                entity_alias: dependencia_by_organismo
                class: App:Dependencia
                entity_field: dependencia
                parent_entity_field: organismo
                parent_form_field: organismo
                choice_label: nombre
                no_result_msg: 'Sin resultados'
                placeholder: '--seleccionar--'
            search_options:
                role: ROLE_USER
                order_field: nombre
                order_direction: ASC