# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'
    mailer_user: 'something@example.com'
    upload_dir: '%kernel.project_dir%/public/uploads/images'
    sonata.user.admin.user.class: App\Admin\UserAdmin
    container.dumper.inline_factories: true

services:
    app.menu_listener:
        class: App\EventListener\MenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'


    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    admin.anexoii:
        class: App\Admin\AnexoiiAdmin
        arguments: [~, App\Entity\Anexoii, App\Controller\AnexoiiAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Anexoii }
        public: true
        calls:
            - [ addChild, ["@admin.item_prefacturacion"]]

    admin.factura:
        class: App\Admin\FacturaAdmin
        arguments: [~, App\Entity\Factura, App\Controller\FacturaAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Factura, show_in_dashboard: false}
        public: true
        calls:
            - [ addChild, ["@admin.item_prefacturacion"]]

    admin.hospital:
        class: App\Admin\HospitalAdmin
        arguments: [~, App\Entity\Hospital, App\Controller\HospitalAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Hospital,  show_in_dashboard: false}
        public: true

    admin.item_prefacturacion:
        class: App\Admin\ItemPrefacturacionAdmin
        arguments: [~, App\Entity\ItemPrefacturacion, App\Controller\ItemPrefacturacionAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Prefacturacion,  show_in_dashboard: false}
        public: true

    admin.nomencla:
        class: App\Admin\NomenclaAdmin
        arguments: [~, App\Entity\Nomencla, App\Controller\NomenclaAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Nomencla }
        public: true

    admin.obras_sociales:
        class: App\Admin\ObrasSocialesAdmin
        arguments: [~, App\Entity\ObrasSociales, App\Controller\ObrasSocialesAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ObrasSociales }
        public: true

    admin.servicios:
        class: App\Admin\ServiciosAdmin
        arguments: [~, App\Entity\Servicios, App\Controller\ServiciosAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Servicios }
        public: true

    admin.pago:
        class: App\Admin\PagoAdmin
        arguments: [~, App\Entity\Pago, App\Controller\PagoAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pago, show_in_dashboard: false}
        public: true

    admin.auditoria_administrativa_cod_cie10:
        class: App\Admin\AuditoriaAdministrativaCodCie10Admin
        arguments: [~, App\Entity\AuditoriaAdministrativaCodCie10, App\Controller\AuditoriaAdministrativaCodCie10AdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: AnexoCie10, show_in_dashboard: false}
        public: true

    admin.cod_cie10:
        class: App\Admin\CodCie10Admin
        arguments: [~, App\Entity\CodCie10, App\Controller\CodCie10AdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cie10 }
        public: true

    admin.cuota:
        class: App\Admin\CuotaAdmin
        arguments: [~, App\Entity\Cuota, App\Controller\CuotaAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cuota, show_in_dashboard: false}
        public: true

    admin.tipopago:
        class: App\Admin\TipopagoAdmin
        arguments: [~, App\Entity\Tipopago, App\Controller\TipopagoAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tipopago }
        public: true

    admin.liquidacion:
        class: App\Admin\LiquidacionAdmin
        arguments: [~, App\Entity\Liquidacion, App\Controller\LiquidacionAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Liquidacion }
        public: true

    admin.estimulo:
        class: App\Admin\EstimuloAdmin
        arguments: [~, App\Entity\Estimulo, App\Controller\EstimuloAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Estimulo }
        public: true

    admin.recibo:
        class: App\Admin\ReciboAdmin
        arguments: [~, App\Entity\Recibo, App\Controller\ReciboAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Recibo }
        public: true

    admin.certificado:
        class: App\Admin\CertificadoAdmin
        arguments: [~, App\Entity\Certificado, App\Controller\CertificadoAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Certificado }
        public: true

    admin.estado:
        class: App\Admin\EstadoAdmin
        arguments: [~, App\Entity\Estado, App\Controller\EstadoAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Estado }
        public: true

    admin.certificado_factura:
        class: App\Admin\CertificadoFacturaAdmin
        arguments: [~, App\Entity\CertificadoFactura, App\Controller\CertificadoFacturaAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CertificadoFactura }
        public: true
